name: Go Test

on:
  # push:
  #   branches: [ "v2" ]
  pull_request:
    branches: ["v2"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27546:27017

      redis:
        image: redis:latest
        ports:
          - 6349:6379
    strategy:
      matrix:
        go-version: [ '1.20' ]

    steps:
      - uses: actions/checkout@v4
      - name: Change to the API directory
        run: cd api
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Print Current Directory
        run: |
          echo "Current Directory: $(pwd)"

      - name: Install dependencies
        run: go mod download

      - name: Run tests integration
        run: go test -v -tags=postgres,redis ./tests/integration

      - name: Run tests unit
        run: go test -v ./tests/unit

      - name: Clean up PostgreSQL and Redis containers
        run: |
          docker stop postgres
          docker stop redis
